### ISSUE TITLE
Cannot open data table in map.apps 4.13.0-SNAPSHOT

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-toc-action-datatable#2]
Currently, data tables constructed the data table toc action cannot be opened in map.apps 4.13.0-SNAPSHOT.

Reproduction:  
- Open mapapps-toc-action-datable project locally, adjusting map.apps version to 4.13.0-SNAPSHOT
- Try to open data table for the layer "Stoerung - Störungen" using the toc action

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-toc-action-datatable/commit/08628b14f3e1e715669b0938a857162c8b01023b
