### ISSUE TITLE
Action wird nicht korrekt im TOC eingebunden

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-toc-action-datatable#4]
Das Bundle dn_tocactiondatatable listet alle Features eines Layers in tabellarischer Form auf, d.h. das Werkzeug ist normal als Action im Layer verfügbar.
In map.apps 4.15.1 ist die Funktion allerdings im Gruppenlayer verfügbar und nicht auf der Layerebene. [map.apps 4.15.1/dn_tocactiondatatable 1.3.1]

Dienst
![dienst](https://github.com/conterra/mapapps-toc-action-datatable/assets/60434030/e2a4af2b-fdd8-47dd-a34e-07158dc71e9d)

Gruppenlayer
![gruppenlayer](https://github.com/conterra/mapapps-toc-action-datatable/assets/60434030/4faf7a31-1331-4641-a751-1f02f92a3ab9)

Layer
![layer](https://github.com/conterra/mapapps-toc-action-datatable/assets/60434030/d7c5e2e6-a1d3-4970-bfbc-8565bc4f0897)

**Comment by matthiasstein** [comment]
Dies kann ich in unserer Testumgebung nicht nachstellen. Könnten Sie mir bitte Ihre App per E-Mail zuschicken?
