### ISSUE TITLE
Features werden hervorgehoben

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-toc-action-datatable#6]
Das Bundle dient zur tabellarischen Darstellung der vorhandenen Attribute eines Layers.

Jedoch werden in der map.apps-Version 4.15.1 in Kombination mit der result-ui die Features beim Öffnen der Tabelle in der Karte hervorgehoben, was im Gegensatz zur Selektion hier nicht gewünscht ist. Zudem verändert sich dabei automatisch unerwünschterweise auch der gewählte Kartenausschnitt.

**Comment by matthiasstein** [comment]
Das Highlighting im result-ui Bundle muss in diesem Fall manuell deaktiviert werden:
```json
"result-api": {
  "TableStateMapVisualizer": {
    "componentEnabled": false
  }
}
```

Dies gilt dann allerdings global für jede Nutzung des Bundles in der App.
